# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Hp\Desktop\информатика\editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(450, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setStatusTip("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_widget = QtWidgets.QWidget(self.widget)
        self.text_widget.setObjectName("text_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.text_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.text_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.text_widget)
        self.btn_widget = QtWidgets.QWidget(self.widget)
        self.btn_widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btn_widget.setAccessibleName("")
        self.btn_widget.setObjectName("btn_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.btn_widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(self.btn_widget)
        self.save_btn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(14)
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius:6px;\n"
"    border:7px;\n"
"\n"
"    \n"
"    background-color: rgb(93, 255, 174);\n"
"    \n"
"    border-color: rgb(0, 200, 255);\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.ext_btn = QtWidgets.QPushButton(self.btn_widget)
        self.ext_btn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(14)
        self.ext_btn.setFont(font)
        self.ext_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ext_btn.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius:6px;\n"
"    border:7px;\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(255, 70, 70);\n"
"    \n"
"    border-color: rgb(0, 200, 255);\n"
"}")
        self.ext_btn.setObjectName("ext_btn")
        self.horizontalLayout_2.addWidget(self.ext_btn)
        self.verticalLayout.addWidget(self.btn_widget)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "editor (beta) - Made in Russia"))
        self.label.setText(_translate("MainWindow", "help: https://vk.com/damil.amrenov"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.ext_btn.setText(_translate("MainWindow", "Exit"))
